name: Test Shortcut PR Validator

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build action
        run: npm run build
      
      - name: Test PR validation
        uses: ./
        with:
          github_auth_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo_name: ${{ github.repository }}
          shortcut_auth_token: ${{ secrets.SHORTCUT_AUTH_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          expected_states: "in progress,to do,ready for review"
